[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "pip list | grep uvicorn"
]

[phases.build]
cmds = [
    "echo 'Build phase completed'",
    "python -c 'import uvicorn; print(f\"uvicorn version: {uvicorn.__version__}\")'"
]

[start]
cmd = "python start.py"