[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install fastapi uvicorn"
]

[phases.build]
cmds = [
    "echo 'Build phase completed'"
]

[start]
cmd = "python start.py"
