version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: russian_bot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (optional, for future caching)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # Telegram AI Bot
  bot:
    build: .
    environment:
      # Database
      DATABASE_URL: postgresql://postgres:password@postgres:5432/russian_bot_db
      
      # Required environment variables (set these in your .env file)
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SUPER_ADMIN_ID: ${SUPER_ADMIN_ID}
      
      # Optional variables with defaults
      WEBHOOK_BASE_URL: ${WEBHOOK_BASE_URL:-}
      WEBHOOK_PATH: ${WEBHOOK_PATH:-/webhook}
      WEBHOOK_SECRET_TOKEN: ${WEBHOOK_SECRET_TOKEN:-}
      PAYMENT_PROVIDER_TOKEN: ${PAYMENT_PROVIDER_TOKEN:-}
      
      # AI Models
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o}
      OPENAI_IMAGE_MODEL: ${OPENAI_IMAGE_MODEL:-dall-e-3}
      OPENAI_TTS_MODEL: ${OPENAI_TTS_MODEL:-tts-1}
      OPENAI_WHISPER_MODEL: ${OPENAI_WHISPER_MODEL:-whisper-1}
      
      # Bot settings
      MAX_HISTORY_MESSAGES: ${MAX_HISTORY_MESSAGES:-16}
      
      # Limits
      FREE_DAILY_MESSAGES: ${FREE_DAILY_MESSAGES:-20}
      FREE_DAILY_IMAGES: ${FREE_DAILY_IMAGES:-5}
      FREE_DAILY_VOICE: ${FREE_DAILY_VOICE:-10}
      PRO_DAILY_MESSAGES: ${PRO_DAILY_MESSAGES:-200}
      PRO_DAILY_IMAGES: ${PRO_DAILY_IMAGES:-50}
      PRO_DAILY_VOICE: ${PRO_DAILY_VOICE:-100}
      PRO_PRICE_RUB: ${PRO_PRICE_RUB:-199}
      TEAM_DAILY_MESSAGES: ${TEAM_DAILY_MESSAGES:-1000}
      TEAM_DAILY_IMAGES: ${TEAM_DAILY_IMAGES:-200}
      TEAM_DAILY_VOICE: ${TEAM_DAILY_VOICE:-500}
      TEAM_PRICE_RUB: ${TEAM_PRICE_RUB:-799}
      
      # Environment
      ENVIRONMENT: ${ENVIRONMENT:-development}
      DEBUG: ${DEBUG:-true}
      PORT: 8000
    
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app:/app/app  # Mount source code for development
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: